version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/sushrut1101/docker:latest

    resource_class: 2xlarge
    steps:
      - checkout

      - run:
          name: Source Vars
          command: |
            sudo apt install neofetch
            neofetch
