version: 2.1
executors:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large

jobs:
  build:
    docker:
      - image: marvelmathesh/docker:rom
    steps: 
      - run:
          name: Syncing
          command: git clone https://github.com/Subhendu-droid/shell-bot-cirrus bot && cd bot && bash bot.sh
          no_output_timeout: 6h
