version: 2.1
executors:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large

jobs:
  build:
    docker:
      - image: marvelmathesh/docker:rom
    steps:
      - run:
          name: Syncing
          command: |
            bash synching.sh
     

      - run:
          name: Cloning
          command: |
            bash cloning.sh
    
      - run:
          name: Clone local repo
          command: |
            git clone https://github.com/Subhendu-droid/shell-bot-cirrus -b main bot

      - run:
          name: Building
          command: bash building.sh
          no_output_timeout: 6h
     
      - run:
          name: Circle loop
          command: |
            git clone https://github.com/Subhendu-droid/shell-bot-cirrus -b main loop
            cd loop || exit 1
            echo $(TZ='Asia/Kolkata' date) >> loop.txt
            git add loop.txt
            git commit -m "Workflow : Loop $(TZ='Asia/Kolkata' date)"
            git push -q https://$GIT_TOKEN@github.com/shell-boy-cirrus HEAD:main
